# Generated by Django 5.1.7 on 2025-05-17 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignaciones', '0008_alter_asignation_attended'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='days_from_last_helper',
            field=models.IntegerField(default=999),
        ),
        migrations.AlterField(
            model_name='person',
            name='days_from_last_asignation',
            field=models.IntegerField(default=999),
        ),
    ]
